---
# Ansible Inventory for Docker/K8s Training
# 20 VMs for hands-on training

all:
  hosts:
    vm-01:
      ansible_host: 192.168.1.101
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-02:
      ansible_host: 192.168.1.102
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-03:
      ansible_host: 192.168.1.103
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-04:
      ansible_host: 192.168.1.104
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-05:
      ansible_host: 192.168.1.105
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-06:
      ansible_host: 192.168.1.106
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-07:
      ansible_host: 192.168.1.107
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-08:
      ansible_host: 192.168.1.108
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-09:
      ansible_host: 192.168.1.109
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-10:
      ansible_host: 192.168.1.110
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-11:
      ansible_host: 192.168.1.111
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-12:
      ansible_host: 192.168.1.112
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-13:
      ansible_host: 192.168.1.113
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-14:
      ansible_host: 192.168.1.114
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-15:
      ansible_host: 192.168.1.115
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-16:
      ansible_host: 192.168.1.116
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-17:
      ansible_host: 192.168.1.117
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-18:
      ansible_host: 192.168.1.118
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-19:
      ansible_host: 192.168.1.119
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    vm-20:
      ansible_host: 192.168.1.120
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  children:
    k3s_cluster:
      hosts:
        vm-[01:20]

